### PR TITLE
Maps and sets up incineration for polymorphic associations.

### LINKED ISSUE #13: Possible bug: Random incineration failures when polymorphic associations are involved
https://www.loom.com/share/83ecdcc3c57a4678919ebd1409303688

To try on local: 
For folks who want to try it out on their local, the branch is `185-add-tests-for-incineration-service` in neeto-crm and the seed value for the failure case is 55054

### PR DESCRIPTION
**Pull request by shreyansh-g24**
FIXES #13

### CODE REVIEW

**Comment by shreyansh-g24** [comment]
@unnitallman _a Please check

**Comment by shreyansh-g24** [comment]
@unnitallman How do I test the changes?

**Comment by chiraggshah** [comment]
@shreyansh-g24 : You can try it out on local. Checkout the branch `185-add-tests-for-incineration-service` from neeto-crm-web. When you run the tests with seed value `55054`, the bug can be reproduced.

**Comment by shreyansh-g24** [comment]
@chiraggshah The test is already passing, I hadn't made any changes to the incineration code in any way in neeto-crm.

**Comment by shreyansh-g24** [comment]
It could be a random success, forgot the seed value.

**Comment by shreyansh-g24** [comment]
@chiraggshah It is also passing with the seed value
`rails test test/models/organization_test.rb --seed 55054`

**Comment by shreyansh-g24** [comment]
`3122` is the failing seed value on my local

```
["Note",
 "CustomFieldValue",
 "CustomField",
 "Attachment",
 "Deal",
 "Person",
 "Company",
 "Taxonomy",
 "User",
 "OrganizationRole",
 "Organization"]
```

This is the order I am getting.

The tests are passing with the updates and failing without the changes.

**Pull request merged**
